# server config
server:
  port: 8080

spring:
# DB config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohgi_restaurant
    username: ohgiraffers
    password: ohgiraffers
# file upload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/
# JAP config
  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


# static resource (image media file) config
## 이미지를 저장할 위치, 응답 시 이미지 주소를 상수값 (@Value) 으로 설정
image:
  add-resource=location: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**
  image-dir: src/main/resources/static/productimgs
  image-url: http://localhost:8080/productimgs/


# security config(jwt) config
jwt:
  secret: bmECAkdVYiztlqellVSMMg6qVLLxjhYFQM9kyEZAYYmY9eAAV/kKFsUY3YMGLa2YNNE51yHOiyo3Acp2LwNy6Q==`

# springdoc open-api config
springdoc:
  swagger-ui:
    path: /swagger-ui.html


# logging config
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace



